### ISSUE TITLE
Remove Serifs on Menu for Windows Platform

### ISSUE THREAD

**Issue by billstrahlend** [calvaryQC/website-public#17]
# Issues
Fix the font to match across all platforms

## Requirements

- [x] Menu Text under Nav Icon has Serif font on Windows Platform
- [x] Menu content has serif font on Windows Platform

**Comment by billstrahlend** [comment]
@tricitymatt Please review on your Windows machine to see if this has been resolved. Thank you.

**Comment by tricitymatt** [comment]
FIXED!!!Thanks bro.  You'll have to let me know how you did that next time I see you at church.  :-)


-------- Original Message --------
Subject: Re: [calvaryQC/website-public] Remove Serifs on Menu for
Windows Platform (#17)

**Comment by billstrahlend** [comment]
Changed the font for the menu and the menu button from `Helvetica Neue` to `Helvetica`
