### ISSUE TITLE
Give Page

### ISSUE THREAD

**Issue by tricitymatt** [calvaryQC/website-public#3]
Requirements:

- [x] Move all current data over
- [x] Format to new layout
- [x] Update data.
- [x] Add PayPal connection
- [x] Add text2give feature

**Comment by billstrahlend** [comment]
Brought in all the existing content and applied to current layout that made sense. Used the "Tab" module to switch between giving options and applied custom CSS to make the tab aesthetics more appealing. Created new categories for giving:

- During Service
- Online
- Mobile
- Check via Direct Mail

Online includes EasyTithe, PayPal, and Automatic Bill Pay. Mobile includes a reference to the Online tab and also provides details for using Text to Give via EasyTithe services and also included their Video demonstration.
